services:
  db:
    image: postgres:18
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-bank_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-bank_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
