# application.yml — главный конфигурационный файл Spring Boot.

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT}

# --------------------------
# Security & encryption keys
# --------------------------

jwt:
  secret-b64: ${JWT_SECRET_B64} # JWT signing key (Base64)

encryption:
  pan-key-b64: ${PAN_AES_KEY_B64} # AES key for card PANs (card numbers)
  attribute-key-b64: ${ATTRIBUTE_AES_KEY_B64} # AES key for AttributeEncryptor

springdoc:
  swagger-ui:
    path: /docs          # UI

  logging:
    level:
      org.springdoc: DEBUG
      org.springframework.web: INFO
